#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : epydoc
Version  : 3.0.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/60/a7/666cb415b0f5d8d5c99f145e03a6005220090d7b77637871ac52c2cabcba/epydoc-3.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/60/a7/666cb415b0f5d8d5c99f145e03a6005220090d7b77637871ac52c2cabcba/epydoc-3.0.1.tar.gz
Summary  : Tool for generating API documentation for Python modules, based on their docstrings
Group    : Development/Tools
License  : MIT
Requires: epydoc-bin = %{version}-%{release}
Requires: epydoc-license = %{version}-%{release}
Requires: epydoc-python = %{version}-%{release}
Requires: epydoc-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
###############################################################
###                         Epydoc                          ###
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~###
### Author: Edward Loper <edloper@gradient.cis.upenn.edu>   ###
### URL: <http://epydoc.sourceforge.net>                    ###
### For license information, see LICENSE.TXT                ###
###############################################################

%package bin
Summary: bin components for the epydoc package.
Group: Binaries
Requires: epydoc-license = %{version}-%{release}

%description bin
bin components for the epydoc package.


%package license
Summary: license components for the epydoc package.
Group: Default

%description license
license components for the epydoc package.


%package python
Summary: python components for the epydoc package.
Group: Default
Requires: epydoc-python3 = %{version}-%{release}

%description python
python components for the epydoc package.


%package python3
Summary: python3 components for the epydoc package.
Group: Default
Requires: python3-core

%description python3
python3 components for the epydoc package.


%prep
%setup -q -n epydoc-3.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554910716
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/epydoc
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/epydoc/LICENSE.txt
cp doc/license.html %{buildroot}/usr/share/package-licenses/epydoc/doc_license.html
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/apirst2html.py
/usr/bin/epydoc
/usr/bin/epydocgui

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/epydoc/LICENSE.txt
/usr/share/package-licenses/epydoc/doc_license.html

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
